from .constants import (
    OFF_PEAK,
    PEAK,
    STANDARD,
    ConnectionTypes,
    FixedChargeTypes,
    RateBillingType,
    HIGH_DEMAND,
    LOW_DEMAND,
    ChargeVoltageType,
    KVA,
    ChargeVoltageType,
)

high_demand_months = [6, 7, 8]

tariff_intervals = {
    "high_demand_months": high_demand_months,
    LOW_DEMAND: {
        0: {0: OFF_PEAK, 1: OFF_PEAK},
        1: {0: OFF_PEAK, 1: OFF_PEAK},
        2: {0: OFF_PEAK, 1: OFF_PEAK},
        3: {0: OFF_PEAK, 1: OFF_PEAK},
        4: {0: OFF_PEAK, 1: OFF_PEAK},
        5: {0: OFF_PEAK, 1: OFF_PEAK},
        6: {0: STANDARD, 1: STANDARD},
        7: {0: PEAK, 1: PEAK},
        8: {0: PEAK, 1: PEAK},
        9: {0: PEAK, 1: PEAK},
        10: {0: STANDARD, 1: STANDARD},
        11: {0: STANDARD, 1: STANDARD},
        12: {0: STANDARD, 1: STANDARD},
        13: {0: STANDARD, 1: STANDARD},
        14: {0: STANDARD, 1: STANDARD},
        15: {0: STANDARD, 1: STANDARD},
        16: {0: STANDARD, 1: STANDARD},
        17: {0: STANDARD, 1: STANDARD},
        18: {0: PEAK, 1: PEAK},
        19: {0: PEAK, 1: PEAK},
        20: {0: STANDARD, 1: STANDARD},
        21: {0: STANDARD, 1: STANDARD},
        22: {0: OFF_PEAK, 1: OFF_PEAK},
        23: {0: OFF_PEAK, 1: OFF_PEAK},
    },
    HIGH_DEMAND: {
        0: {0: OFF_PEAK, 1: OFF_PEAK},
        1: {0: OFF_PEAK, 1: OFF_PEAK},
        2: {0: OFF_PEAK, 1: OFF_PEAK},
        3: {0: OFF_PEAK, 1: OFF_PEAK},
        4: {0: OFF_PEAK, 1: OFF_PEAK},
        5: {0: OFF_PEAK, 1: OFF_PEAK},
        6: {0: PEAK, 1: PEAK},
        7: {0: PEAK, 1: PEAK},
        8: {0: PEAK, 1: PEAK},
        9: {0: STANDARD, 1: STANDARD},
        10: {0: STANDARD, 1: STANDARD},
        11: {0: STANDARD, 1: STANDARD},
        12: {0: STANDARD, 1: STANDARD},
        13: {0: STANDARD, 1: STANDARD},
        14: {0: STANDARD, 1: STANDARD},
        15: {0: STANDARD, 1: STANDARD},
        16: {0: STANDARD, 1: STANDARD},
        17: {0: PEAK, 1: PEAK},
        18: {0: PEAK, 1: PEAK},
        19: {0: STANDARD, 1: STANDARD},
        20: {0: STANDARD, 1: STANDARD},
        21: {0: STANDARD, 1: STANDARD},
        22: {0: OFF_PEAK, 1: OFF_PEAK},
        23: {0: OFF_PEAK, 1: OFF_PEAK},
    },
}

coe_tariff_d_2020_2021_map = {
    "high_demand_months": [6, 7, 8],
    LOW_DEMAND: {
        0: {0: OFF_PEAK, 1: OFF_PEAK},
        1: {0: OFF_PEAK, 1: OFF_PEAK},
        2: {0: OFF_PEAK, 1: OFF_PEAK},
        3: {0: OFF_PEAK, 1: OFF_PEAK},
        4: {0: OFF_PEAK, 1: OFF_PEAK},
        5: {0: OFF_PEAK, 1: OFF_PEAK},
        6: {0: STANDARD, 1: STANDARD},
        7: {0: PEAK, 1: PEAK},
        8: {0: PEAK, 1: PEAK},
        9: {0: PEAK, 1: PEAK},
        10: {0: STANDARD, 1: STANDARD},
        11: {0: STANDARD, 1: STANDARD},
        12: {0: STANDARD, 1: STANDARD},
        13: {0: STANDARD, 1: STANDARD},
        14: {0: STANDARD, 1: STANDARD},
        15: {0: STANDARD, 1: STANDARD},
        16: {0: STANDARD, 1: STANDARD},
        17: {0: STANDARD, 1: STANDARD},
        18: {0: PEAK, 1: PEAK},
        19: {0: PEAK, 1: PEAK},
        20: {0: STANDARD, 1: STANDARD},
        21: {0: STANDARD, 1: STANDARD},
        22: {0: OFF_PEAK, 1: OFF_PEAK},
        23: {0: OFF_PEAK, 1: OFF_PEAK},
    },
    HIGH_DEMAND: {
        0: {0: OFF_PEAK, 1: OFF_PEAK},
        1: {0: OFF_PEAK, 1: OFF_PEAK},
        2: {0: OFF_PEAK, 1: OFF_PEAK},
        3: {0: OFF_PEAK, 1: OFF_PEAK},
        4: {0: OFF_PEAK, 1: OFF_PEAK},
        5: {0: OFF_PEAK, 1: OFF_PEAK},
        6: {0: PEAK, 1: PEAK},
        7: {0: PEAK, 1: PEAK},
        8: {0: PEAK, 1: PEAK},
        9: {0: STANDARD, 1: STANDARD},
        10: {0: STANDARD, 1: STANDARD},
        11: {0: STANDARD, 1: STANDARD},
        12: {0: STANDARD, 1: STANDARD},
        13: {0: STANDARD, 1: STANDARD},
        14: {0: STANDARD, 1: STANDARD},
        15: {0: STANDARD, 1: STANDARD},
        16: {0: STANDARD, 1: STANDARD},
        17: {0: PEAK, 1: PEAK},
        18: {0: PEAK, 1: PEAK},
        19: {0: STANDARD, 1: STANDARD},
        20: {0: STANDARD, 1: STANDARD},
        21: {0: STANDARD, 1: STANDARD},
        22: {0: OFF_PEAK, 1: OFF_PEAK},
        23: {0: OFF_PEAK, 1: OFF_PEAK},
    },
}

coe_tariff_e_2020_2021 = {
    "high_demand_months": [6, 7, 8],
    LOW_DEMAND: {
        0: {0: OFF_PEAK, 1: OFF_PEAK},
        1: {0: OFF_PEAK, 1: OFF_PEAK},
        2: {0: OFF_PEAK, 1: OFF_PEAK},
        3: {0: OFF_PEAK, 1: OFF_PEAK},
        4: {0: OFF_PEAK, 1: OFF_PEAK},
        5: {0: OFF_PEAK, 1: OFF_PEAK},
        6: {0: STANDARD, 1: STANDARD},
        7: {0: PEAK, 1: PEAK},
        8: {0: PEAK, 1: PEAK},
        9: {0: PEAK, 1: PEAK},
        10: {0: STANDARD, 1: STANDARD},
        11: {0: STANDARD, 1: STANDARD},
        12: {0: STANDARD, 1: STANDARD},
        13: {0: STANDARD, 1: STANDARD},
        14: {0: STANDARD, 1: STANDARD},
        15: {0: STANDARD, 1: STANDARD},
        16: {0: STANDARD, 1: STANDARD},
        17: {0: STANDARD, 1: STANDARD},
        18: {0: PEAK, 1: PEAK},
        19: {0: PEAK, 1: PEAK},
        20: {0: STANDARD, 1: STANDARD},
        21: {0: STANDARD, 1: STANDARD},
        22: {0: OFF_PEAK, 1: OFF_PEAK},
        23: {0: OFF_PEAK, 1: OFF_PEAK},
    },
    HIGH_DEMAND: {
        0: {0: OFF_PEAK, 1: OFF_PEAK},
        1: {0: OFF_PEAK, 1: OFF_PEAK},
        2: {0: OFF_PEAK, 1: OFF_PEAK},
        3: {0: OFF_PEAK, 1: OFF_PEAK},
        4: {0: OFF_PEAK, 1: OFF_PEAK},
        5: {0: OFF_PEAK, 1: OFF_PEAK},
        6: {0: PEAK, 1: PEAK},
        7: {0: PEAK, 1: PEAK},
        8: {0: PEAK, 1: PEAK},
        9: {0: STANDARD, 1: STANDARD},
        10: {0: STANDARD, 1: STANDARD},
        11: {0: STANDARD, 1: STANDARD},
        12: {0: STANDARD, 1: STANDARD},
        13: {0: STANDARD, 1: STANDARD},
        14: {0: STANDARD, 1: STANDARD},
        15: {0: STANDARD, 1: STANDARD},
        16: {0: STANDARD, 1: STANDARD},
        17: {0: PEAK, 1: PEAK},
        18: {0: PEAK, 1: PEAK},
        19: {0: STANDARD, 1: STANDARD},
        20: {0: STANDARD, 1: STANDARD},
        21: {0: STANDARD, 1: STANDARD},
        22: {0: OFF_PEAK, 1: OFF_PEAK},
        23: {0: OFF_PEAK, 1: OFF_PEAK},
    },
}

tariff_a = {
    "region": "coe",
    "name": "tariff_a",
    "code": "coe_tariff_a_2020_2021",
    "display_name": "City of Ekhuruleni, 1-JUL-20--30-JUN-21 Tariff_A",
    "tariff_map": [],
    "high_demand_months": [6, 7, 8],
    "currency": "rand",
    "currency_symbol": "R",
    "vat_rate": 0.15,
    "country": "SA",
    "period_start": "2020-07-01",
    "period_end": "2021-06-30",
    "meta": {
        "description": "Small business only",
        "description_extra": "This tariff will suit low consumption micro business customers "
        "who are on prepayment or postpaid metering",
        "connections": [
            ConnectionTypes.SINGLE_PHASE_230_V,
            ConnectionTypes.MULTI_PHASE_400_OR_230_V,
        ],
        "capacity_max": "80A",
    },
    "meter_voltage_types": [
        ChargeVoltageType.POST_PAID_METERING,
        ChargeVoltageType.PREPAID_METERING,
    ],
    "charges": [
        {
            "name": "fixed_charge",
            "rate_billing_type": RateBillingType.PER_MONTH,
            "types": {
                ChargeVoltageType.POST_PAID_METERING: 44.46,
                ChargeVoltageType.PREPAID_METERING: 20,
            },
        },
        {
            "name": "energy_charge",
            "rate_billing_type": RateBillingType.PER_KWH,
            "types": {
                HIGH_DEMAND: {
                    ChargeVoltageType.POST_PAID_METERING: {
                        PEAK: 2.3382,
                        OFF_PEAK: 2.3382,
                        STANDARD: 2.3382,
                    },
                    ChargeVoltageType.PREPAID_METERING: {
                        PEAK: 2.3382,
                        OFF_PEAK: 2.3382,
                        STANDARD: 2.3382,
                    },
                },
                LOW_DEMAND: {
                    ChargeVoltageType.POST_PAID_METERING: {
                        PEAK: 2.3382,
                        OFF_PEAK: 2.3382,
                        STANDARD: 2.3382,
                    },
                    ChargeVoltageType.PREPAID_METERING: {
                        PEAK: 2.3382,
                        OFF_PEAK: 2.3382,
                        STANDARD: 2.3382,
                    },
                },
            },
        },
        {
            "name": "internet_based_consumption_display",
            "rate_billing_type": RateBillingType.PER_MONTH,
            "types": {
                ChargeVoltageType.POST_PAID_METERING: 196.13,
                ChargeVoltageType.PREPAID_METERING: 196.13,
            },
        },
    ],
}

tariff_c = {
    "region": "coe",
    "code": "coe_tariff_c_2020_2021",
    "name": "tariff_c",
    "display_name": "City of Ekhuruleni, 1-JUL-20--30-JUN-21 Tariff_C",
    "tariff_map": [],
    "high_demand_months": [6, 7, 8],
    "currency": "rand",
    "currency_symbol": "R",
    "vat_rate": 0.15,
    "country": "SA",
    "period_start": "2020-07-01",
    "period_end": "2021-06-30",
    "expires": "2021-06-30",
    "meta": {
        "description": "Small business only",
        "description_extra": "This tariff will suit low consumption micro business customers "
        "who are on prepayment or postpaid metering",
        "connections": [
            ConnectionTypes.SINGLE_PHASE_230_V,
            ConnectionTypes.MULTI_PHASE_400_OR_230_V,
        ],
        "capacity_max": "11kV",
    },
    "meter_voltage_types": [
        ChargeVoltageType.ANY_230_400_V,
        ChargeVoltageType.LESS_11KV_230_400_V,
        ChargeVoltageType.DIRECT_FROM_SUBSTATIION_230_400_V,
    ],
    "charges": [
        {
            "name": "fixed_charge",
            "rate_billing_type": RateBillingType.PER_MONTH,
            "types": {
                ChargeVoltageType.ANY_230_400_V: 2273.82,
                ChargeVoltageType.DIRECT_FROM_SUBSTATIION_230_400_V: 2273.82,
                ChargeVoltageType.LESS_11KV_230_400_V: 3227.17,
            },
        },
        {
            "name": "demand_charge",
            "rate_billing_type": RateBillingType.PER_MAX_KVA_PER_MONTH,
            "types": {
                HIGH_DEMAND: {
                    ChargeVoltageType.ANY_230_400_V: 168.48,
                    ChargeVoltageType.LESS_11KV_230_400_V: 165.46,
                    ChargeVoltageType.DIRECT_FROM_SUBSTATIION_230_400_V: 162.44,
                },
                LOW_DEMAND: {
                    ChargeVoltageType.ANY_230_400_V: 140.40,
                    ChargeVoltageType.LESS_11KV_230_400_V: 137.91,
                    ChargeVoltageType.DIRECT_FROM_SUBSTATIION_230_400_V: 135.37,
                },
            },
            "base_rate": {},
        },
        {
            "name": "network_access_charge",
            "rate_billing_type": RateBillingType.PER_MAX_KVA_PER_YEAR,
            "types": {
                ChargeVoltageType.ANY_230_400_V: 48.85,
                ChargeVoltageType.LESS_11KV_230_400_V: 47.99,
                ChargeVoltageType.DIRECT_FROM_SUBSTATIION_230_400_V: 47.12,
            },
            "base_rate": {
                "rate_billing_type": RateBillingType.PER_MONTH,
                "units": 25,
                "unit_type": KVA,
            },
        },
        {
            "name": "energy_charge",
            "rate_billing_type": RateBillingType.PER_KWH,
            "types": {
                HIGH_DEMAND: {
                    ChargeVoltageType.ANY_230_400_V: {
                        PEAK: 2.2518,
                        OFF_PEAK: 2.2518,
                        STANDARD: 2.2518,
                    },
                    ChargeVoltageType.DIRECT_FROM_SUBSTATIION_230_400_V: {
                        PEAK: 2.2098,
                        OFF_PEAK: 2.2098,
                        STANDARD: 2.2098,
                    },
                    ChargeVoltageType.LESS_11KV_230_400_V: {
                        PEAK: 2.1680,
                        OFF_PEAK: 2.1680,
                        STANDARD: 2.1680,
                    },
                },
                LOW_DEMAND: {
                    ChargeVoltageType.ANY_230_400_V: {
                        PEAK: 1.3468,
                        OFF_PEAK: 1.3468,
                        STANDARD: 1.3468,
                    },
                    ChargeVoltageType.DIRECT_FROM_SUBSTATIION_230_400_V: {
                        PEAK: 1.3229,
                        OFF_PEAK: 1.3229,
                        STANDARD: 1.3229,
                    },
                    ChargeVoltageType.LESS_11KV_230_400_V: {
                        PEAK: 1.2987,
                        OFF_PEAK: 1.2987,
                        STANDARD: 1.2987,
                    },
                },
            },
            "base_rate": {},
        },
    ],
}

tariff_d = {
    "region": "coe",
    "code": "coe_tariff_d_2020_2021",
    "name": "tariff_d",
    "display_name": "City of Ekhuruleni, 1-JUL-20--30-JUN-21 tariff_d",
    "tariff_map": coe_tariff_d_2020_2021_map,
    "high_demand_months": [6, 7, 8],
    "currency": "rand",
    "currency_symbol": "R",
    "vat_rate": 0.15,
    "country": "SA",
    "period_start": "2020-07-01",
    "period_end": "2021-06-30",
    "expires": "2021-06-30",
    "peak_rating": True,
    "meta": {
        "description": "Large business and industrial",
        "description_extra": "This tariff is available for bulk supplies at any voltage and with a capacity of at least"
        "1 MVA and a network access charge of at least 1 MVA over the previous 12 months.",
        "description_emphasis": " Existing customers on this tariff, with a previous 12 months rolling NAC of less than 1 MVA will be moved to Tariff E.",
        "connections": [
            ConnectionTypes.MIN_CAPACITY_1MVA,
            ConnectionTypes.MULTI_PHASE_400_OR_230_V,
        ],
        "capacity_max": "11kV",
    },
    "meter_voltage_types": [
        ChargeVoltageType.DIRECT_FROM_SUBSTATIION_230_400_V,
        ChargeVoltageType.LESS_11KV_230_400_V,
        ChargeVoltageType.CAPACITY_EXCEED_11KV,
    ],
    "charges": [
        {
            "name": "fixed_charge",
            "rate_billing_type": RateBillingType.PER_MONTH,
            "types": {
                ChargeVoltageType.CAPACITY_EXCEED_11KV: 4847.46,
                ChargeVoltageType.LESS_11KV_230_400_V: 3225.17,
                ChargeVoltageType.DIRECT_FROM_SUBSTATIION_230_400_V: 3225.17,
            },
        },
        {
            "name": "demand_charge",
            "rate_billing_type": RateBillingType.PER_MAX_KVA_PER_MONTH,
            "types": {
                HIGH_DEMAND: {
                    ChargeVoltageType.DIRECT_FROM_SUBSTATIION_230_400_V: 79.63,
                    ChargeVoltageType.LESS_11KV_230_400_V: 78.1,
                    ChargeVoltageType.CAPACITY_EXCEED_11KV: 43.2,
                },
                LOW_DEMAND: {
                    ChargeVoltageType.DIRECT_FROM_SUBSTATIION_230_400_V: 79.63,
                    ChargeVoltageType.LESS_11KV_230_400_V: 78.1,
                    ChargeVoltageType.CAPACITY_EXCEED_11KV: 43.2,
                },
            },
            "base_rate": {},
        },
        {
            "name": "network_access_charge",
            "rate_billing_type": RateBillingType.PER_MAX_KVA_PER_YEAR,
            "types": {
                ChargeVoltageType.DIRECT_FROM_SUBSTATIION_230_400_V: 47.78,
                ChargeVoltageType.LESS_11KV_230_400_V: 46.91,
                ChargeVoltageType.CAPACITY_EXCEED_11KV: 43.42,
            },
            "base_rate": {
                "rate_billing_type": RateBillingType.PER_MONTH,
                "units": 25,
                "unit_type": KVA,
            },
        },
        {
            "name": "energy_charge",
            "rate_billing_type": RateBillingType.PER_KWH,
            "types": {
                HIGH_DEMAND: {
                    ChargeVoltageType.DIRECT_FROM_SUBSTATIION_230_400_V: {
                        PEAK: 4.8526,
                        OFF_PEAK: 1.0267,
                        STANDARD: 1.7025,
                    },
                    ChargeVoltageType.LESS_11KV_230_400_V: {
                        PEAK: 4.7625,
                        OFF_PEAK: 1.6756,
                        STANDARD: 1.0082,
                    },
                    ChargeVoltageType.CAPACITY_EXCEED_11KV: {
                        PEAK: 4.4142,
                        OFF_PEAK: 1.5495,
                        STANDARD: 0.9339,
                    },
                },
                LOW_DEMAND: {
                    ChargeVoltageType.DIRECT_FROM_SUBSTATIION_230_400_V: {
                        PEAK: 1.8041,
                        OFF_PEAK: 1.1835,
                        STANDARD: 0.9339,
                    },
                    ChargeVoltageType.LESS_11KV_230_400_V: {
                        PEAK: 1.7717,
                        OFF_PEAK: 1.1619,
                        STANDARD: 0.9163,
                    },
                    ChargeVoltageType.CAPACITY_EXCEED_11KV: {
                        PEAK: 1.6404,
                        OFF_PEAK: 1.0770,
                        STANDARD: 0.8482,
                    },
                },
            },
            "base_rate": {},
        },
    ],
}
